config/routes.rb
Fisica::Application.routes.draw do
  resources :temas

end

app/models/tema.rb
class Tema < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
#comentario
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temas }
    end
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
    @tema = Tema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tema }
    end
  end

  # GET /temas/new
  # GET /temas/new.json
  def new
    @tema = Tema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tema }
    end
  end

  # GET /temas/1/edit
  def edit
    @tema = Tema.find(params[:id])
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(params[:tema])

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render json: @tema, status: :created, location: @tema }
      else
        format.html { render action: "new" }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /temas/1
  # PUT /temas/1.json
  def update
    @tema = Tema.find(params[:id])

    respond_to do |format|
      if @tema.update_attributes(params[:tema])
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema = Tema.find(params[:id])
    @tema.destroy

    respond_to do |format|
      format.html { redirect_to temas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fisica</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/temas/_form.html.erb
<%= form_for(@tema) do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% @tema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<h1>Editing tema</h1>

<%= render 'form' %>

<%= link_to 'Show', @tema %> |
<%= link_to 'Back', temas_path %>

app/views/temas/index.html.erb
<h1>Listing temas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @temas.each do |tema| %>
  <tr>
    <td><%= tema.nombre %></td>
    <td><%= tema.descripcion %></td>
    <td><%= link_to 'Show', tema %></td>
    <td><%= link_to 'Edit', edit_tema_path(tema) %></td>
    <td><%= link_to 'Destroy', tema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tema', new_tema_path %>

app/views/temas/new.html.erb
<h1>New tema</h1>

<%= render 'form' %>

<%= link_to 'Back', temas_path %>

app/views/temas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @tema.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @tema.descripcion %>
</p>


<%= link_to 'Edit', edit_tema_path(@tema) %> |
<%= link_to 'Back', temas_path %>